name: detective
description: Mystery psychological game.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^8.1.0
  flutter_phoenix: ^1.1.1
  flutter_snake_navigationbar: ^0.6.1
  flutter_staggered_grid_view: ^0.6.2
  fluttermoji: ^1.0.2
  get: ^4.6.6
  ionicons: ^0.2.2
  logging: ^1.2.0
  flutter_chess_board: ^1.0.1
  chess: ^0.7.0
  stockfish: ^1.0.0
  localstorage: ^4.0.1+4
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatars/
    - assets/images/common/
    - assets/images/intro/
    - assets/images/map/
    - assets/images/game/
    # - assets/games/chess/pieces/
  fonts:
    - family: aisa
      fonts:
        - asset: assets/fonts/aisa.otf
